### ISSUE TITLE
Parsing error with 48 well plate and robotics but no microfluidics

### ISSUE THREAD

**Issue by sleweke-bayer** [JuBiotech/bletl#70]
Hey,

we ran some experiments on a BioLector Pro using a 48 well plate and a pipetting robot (with RoboLector Agent), but without microfluidics.

When importing the file with
```python
bletl.parse('bug.csv')
```
we get this error:
```
Traceback (most recent call last):
  File "/Users/xyz/Projects/bletl/run.py", line 5, in <module>
    bldata = bletl.parse('bug.csv')
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/Projects/bletl/bletl/bletl/core.py", line 263, in parse
    data = _parse(
           ^^^^^^^
  File "/Users/xyz/Projects/bletl/bletl/bletl/core.py", line 141, in _parse
    data = parser.parse(
           ^^^^^^^^^^^^^
  File "/Users/xyz/Projects/bletl/bletl/bletl/parsing/blpro.py", line 77, in parse
    bld.fluidics = extract_fluidics(data)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xyz/Projects/bletl/bletl/bletl/parsing/blpro.py", line 376, in extract_fluidics
    df["well"] = [_MF_WELL_NUMM_TO_ID[w] for w in df["well"]]
                  ~~~~~~~~~~~~~~~~~~~^^^
KeyError: 33
```

I have attached the sample file (data censored, but structure intact).
[bug.csv](https://github.com/user-attachments/files/16725155/bug.csv)

**Comment by michaelosthege** [comment]
Hi @sleweke-bayer thanks for the test dataset! I will investigate this in the coming days.
